name: Auto Linter

on:
  push:
    paths:
      - "**/*.py"

jobs:
  code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff
        run: ruff check .
      - name: check the files for linting
        run:  ruff check .
      
    
       
